name: Metrics
on:
  # Schedule updates (each hour)
  schedule: 
    - cron: '* 1,13,21 * * *'
  push:
    branches:
      - "master"
      - "main"
      - "release"
      - "**"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          
          user: nathan130200
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_activity: yes
          plugin_activity_days: 60
          plugin_activity_filter: all
          plugin_activity_limit: 10
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_lines: yes                                 # Limit to 4 entries
          plugin_projects_descriptions: yes                           # Display projects descriptions
          plugin_followup: yes
          plugin_followup_sections: repositories, user #
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 60        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          
          
          # WakaTime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      # Required
          plugin_wakatime_days: 30                                   # Display last week stats
          plugin_wakatime_sections: time, languages, editors, os # Display time and projects sections, along with projects graphs
          plugin_wakatime_limit: 5                                  # Show 4 entries per graph
          plugin_wakatime_url: https://wakatime.com                 # Wakatime url endpoint
          plugin_wakatime_user: FRNathan13                         # User
