name: Metrics
on:
  # Schedule updates (each hour)
  schedule: 
    - cron: '* 1,13,21 * * *'
  push:
    branches:
      - "master"
      - "main"
      - "release"
      - "**"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: nathan130200
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Gits
          plugin_gists: yes
          
          # Activity 
          plugin_activity: no
          #plugin_activity_days: 60
          #plugin_activity_filter: all
          #plugin_activity_limit: 10
          
          # ISO Canlendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Languages
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 2%
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 30
          plugin_languages_details: lines, percentage
          
          # Lines
          plugin_lines: yes
          
          # Project Descriptions
          plugin_projects_descriptions: no
          
          # Follow Up!
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          
          # Habits
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 60
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          # WakaTime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 30
          plugin_wakatime_sections: time, languages, editors, os
          plugin_wakatime_limit: 5
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: FRNathan13
